# Amazon SageMaker Batch Transform: Associate prediction results with their corresponding input records

---

This notebook's CI test result for us-west-2 is as follows. CI test results in other regions can be found at the end of the notebook. 

![This us-west-2 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/us-west-2/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

---

_**Use SageMaker's XGBoost to train a binary classification model and for a list of tumors in batch file, predict if each is malignant**_

_**It also shows how to use the input output joining / filter feature in Batch transform in details**_

---



## Background
This purpose of this notebook is to train a model using SageMaker's XGBoost and UCI's breast cancer diagnostic data set to illustrate at how to run batch inferences and how to use the Batch Transform I/O join feature. UCI's breast cancer diagnostic data set is available at https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29. The data set is also available on Kaggle at https://www.kaggle.com/uciml/breast-cancer-wisconsin-data. The purpose here is to use this data set to build a predictve model of whether a breast mass image indicates benign or malignant tumor. 



---

## Setup

Let's start by specifying:

* The SageMaker role arn used to give training and batch transform access to your data. The snippet below will use the same role used by your SageMaker notebook instance. Otherwise, specify the full ARN of a role with the SageMakerFullAccess policy attached.
* The S3 bucket that you want to use for training and storing model objects.

In [1]:
!pip3 install -U sagemaker

Collecting sagemaker
  Downloading sagemaker-3.23.0-py3-none-any.whl.metadata (20 kB)
Collecting sagemaker-core<3.0.0,>=2.23.0 (from sagemaker)
  Downloading sagemaker_core-2.23.0-py3-none-any.whl.metadata (5.7 kB)
Collecting sagemaker-train<2.0.0,>=1.23.0 (from sagemaker)
  Downloading sagemaker_train-1.23.0-py3-none-any.whl.metadata (8.2 kB)
Collecting sagemaker-serve<2.0.0,>=1.23.0 (from sagemaker)
  Downloading sagemaker_serve-1.23.0-py3-none-any.whl.metadata (14 kB)
Collecting sagemaker-mlops<2.0.0,>=1.23.0 (from sagemaker)
  Downloading sagemaker_mlops-1.23.0-py3-none-any.whl.metadata (19 kB)
Collecting boto3<2.0.0,>=1.43.90 (from sagemaker-core<3.0.0,>=2.23.0->sagemaker)
  Downloading boto3-1.43.103-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.13.4)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (6.0.3)
Requirement already satisfied: jsonschema<5.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (4.23.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (4.11.3)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (4.0.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (6.10.0)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (4.16.0)
Requirement already satisfied: pytz>=2021.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2024.2)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.34.2)
Requirement already satisfied: attrs>=20.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (26.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (25.0)
Requirement already satisfied: protobuf<7.0.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (6.31.1)
Requirement already satisfied: pandas>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.3.3)
Requirement already satisfied: numpy>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.26.4)
Requirement already satisfied: smdebug_rulesconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.0.1)
Requirement already satisfied: schema>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.7.8)
Requirement already satisfied: omegaconf>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.3.1)
Requirement already satisfied: scipy>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.16.3)
Requirement already satisfied: cloudpickle>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (3.1.2)
Requirement already satisfied: paramiko>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (5.0.0)
Requirement already satisfied: tblib>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (3.2.2)
Requirement already satisfied: cryptography>=46.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.23.0->sagemaker) (46.0.7)
Collecting botocore<1.44.0,>=1.43.103 (from boto3<2.0.0,>=1.43.90->sagemaker-core<3.0.0,>=2.23.0->sagemaker)
  Downloading botocore-1.43.103-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.43.90->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.43.90->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.19.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.44.0,>=1.43.103->boto3<2.0.0,>=1.43.90->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.44.0,>=1.43.103->boto3<2.0.0,>=1.43.90->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.26.20)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (4.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.4.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.103->boto3<2.0.0,>=1.43.90->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (3.19)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2.21.0)
Requirement already satisfied: pyiceberg>=0.8.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.23.0->sagemaker) (0.11.1)
Requirement already satisfied: pyarrow>=14.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.23.0->sagemaker) (21.0.0)
Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.23.0->sagemaker) (2026.6.0)
Requirement already satisfied: deepdiff in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (9.1.0)
Requirement already satisfied: mlflow in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.15.1)
Requirement already satisfied: sagemaker_schema_inference_artifacts in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.0.5)
Requirement already satisfied: pytest in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (9.1.1)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (4.70.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (7.1.3)
Requirement already satisfied: tritonclient[http] in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (2.41.1)
Requirement already satisfied: onnx in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.20.0)
Requirement already satisfied: onnxruntime in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.28.0)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (2.8.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.23.0->sagemaker) (3.4.3)
Requirement already satisfied: jinja2<4.0,>=3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.23.0->sagemaker) (3.1.6)
Requirement already satisfied: sagemaker-mlflow<1.0.0,>=0.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.23.0->sagemaker) (0.5.0)
Requirement already satisfied: nest_asyncio>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.23.0->sagemaker) (1.6.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.23.0->sagemaker) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.23.0->sagemaker) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<4.0,>=3.0->sagemaker-train<2.0.0,>=1.23.0->sagemaker) (3.0.3)
Requirement already satisfied: Flask-CORS<7 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (6.0.5)
Requirement already satisfied: Flask<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.14.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.19.1)
Requirement already satisfied: cachetools<8,>=5.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (8.2.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.132.0)
Requirement already satisfied: docker<8,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (7.2.0)
Requirement already satisfied: fastapi<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.141.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.1.59)
Requirement already satisfied: gunicorn<27 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (26.1.0)
Requirement already satisfied: huey<4,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.3.4)
Requirement already satisfied: matplotlib<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.10.9)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.43.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.43.0)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.2.3)
Requirement already satisfied: scikit-learn<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.7.2)
Requirement already satisfied: skops<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (2.0.52)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.5.0)
Requirement already satisfied: starlette<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.6.0)
Requirement already satisfied: uvicorn<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.52.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4,>=3.7.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4,>=3.7.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4,>=3.7.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4,>=3.7.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4,>=3.7.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4,>=3.7.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.24.5)
Requirement already satisfied: Mako in /opt/conda/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.4.1)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.12/site-packages (from cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (1.17.1)
Requirement already satisfied: google-auth~=2.0 in /opt/conda/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (2.56.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.0.5)
Requirement already satisfied: blinker>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (2.2.0)
Requirement already satisfied: werkzeug>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.5.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in /opt/conda/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.64b0)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (2026.3)
Requirement already satisfied: mlflow-skinny>=2.8 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlflow<1.0.0,>=0.0.1->sagemaker-train<2.0.0,>=1.23.0->sagemaker) (3.15.1)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker)
  Using cached prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (3.5.5)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette<2->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (4.14.2)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn<1->mlflow->sagemaker-serve<2.0.0,>=1.23.0->sagemaker) (0.16.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=1.14->cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (3.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.23.0->sagemaker) (0.1.2)

In [10]:
%pip install 'sagemaker<3.0' -q

Note: you may need to restart the kernel to use updated packages.

In [ ]:
import os
os._exit(0)

In [1]:
import os
import boto3
import sagemaker
from sagemaker import get_execution_role  # Explicit import

role = sagemaker.get_execution_role()
sess = sagemaker.Session()
region = sess.boto_region_name

bucket = sess.default_bucket()
prefix = "DEMO-breast-cancer-prediction-xgboost-highlevel"

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

/opt/conda/lib/python3.12/site-packages/sagemaker/__init__.py:86: SageMakerV2DeprecationWarning: You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation()
You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.

---
## Data sources

> Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

> Breast Cancer Wisconsin (Diagnostic) Data Set [https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)].

> _Also see:_ Breast Cancer Wisconsin (Diagnostic) Data Set [https://www.kaggle.com/uciml/breast-cancer-wisconsin-data].

## Data preparation


Let's download the data and save it in the local folder with the name data.csv and take a look at it.

In [2]:
import pandas as pd
import numpy as np

s3 = boto3.client("s3")

filename = "wdbc.csv"
s3.download_file(
    f"sagemaker-example-files-prod-{region}", "datasets/tabular/breast_cancer/wdbc.csv", filename
)
data = pd.read_csv(filename, header=None)

# specify columns extracted from wbdc.names
data.columns = [
    "id",
    "diagnosis",
    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean",
    "concavity_mean",
    "concave points_mean",
    "symmetry_mean",
    "fractal_dimension_mean",
    "radius_se",
    "texture_se",
    "perimeter_se",
    "area_se",
    "smoothness_se",
    "compactness_se",
    "concavity_se",
    "concave points_se",
    "symmetry_se",
    "fractal_dimension_se",
    "radius_worst",
    "texture_worst",
    "perimeter_worst",
    "area_worst",
    "smoothness_worst",
    "compactness_worst",
    "concavity_worst",
    "concave points_worst",
    "symmetry_worst",
    "fractal_dimension_worst",
]

# save the data
data.to_csv("data.csv", sep=",", index=False)

data.sample(8)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
85,8612399,M,18.46,18.52,121.10,1075.0,0.09874,0.10530,0.133500,0.087950,...,22.93,27.68,152.20,1603.0,0.13980,0.20890,0.31570,0.16420,0.3695,0.08579
223,8812877,M,15.75,20.25,102.60,761.3,0.10250,0.12040,0.114700,0.064620,...,19.56,30.29,125.90,1088.0,0.15520,0.44800,0.39760,0.14790,0.3993,0.10640
320,894604,B,10.25,16.18,66.52,324.2,0.10610,0.11110,0.067260,0.039650,...,11.28,20.61,71.53,390.4,0.14020,0.23600,0.18980,0.09744,0.2608,0.09702
239,88330202,M,17.46,39.28,113.40,920.6,0.09812,0.12980,0.141700,0.088110,...,22.51,44.87,141.20,1408.0,0.13650,0.37350,0.32410,0.20660,0.2853,0.08496
536,91979701,M,14.27,22.55,93.77,629.8,0.10380,0.11540,0.146300,0.061390,...,15.29,34.27,104.30,728.3,0.13800,0.27330,0.42340,0.13620,0.2698,0.08351
172,87164,M,15.46,11.89,102.50,736.9,0.12570,0.15550,0.203200,0.109700,...,18.79,17.04,125.00,1102.0,0.15310,0.35830,0.58300,0.18270,0.3216,0.10100
308,893526,B,13.50,12.71,85.69,566.2,0.07376,0.03614,0.002758,0.004419,...,14.97,16.94,95.48,698.7,0.09023,0.05836,0.01379,0.02210,0.2267,0.06192
256,88649001,M,19.55,28.77,133.60,1207.0,0.09260,0.20630,0.178400,0.114400,...,25.05,36.27,178.60,1926.0,0.12810,0.53290,0.42510,0.19410,0.2818,0.10050

#### Key observations:
* The data has 569 observations and 32 columns.
* The first field is the 'id' attribute that we will want to drop before batch inference and add to the final inference output next to the probability of malignancy.
* Second field, 'diagnosis', is an indicator of the actual diagnosis ('M' = Malignant; 'B' = Benign).
* There are 30 other numeric features that we will use for training and inferencing.

Let's replace the M/B diagnosis with a 1/0 boolean value.

In [9]:
data["diagnosis"] = data["diagnosis"].apply(lambda x: ((x == "M")) + 0)
data.sample(8)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
384,902727,0,13.28,13.72,85.79,541.8,0.08363,0.08575,0.05077,0.02864,...,14.24,17.37,96.59,623.7,0.1166,0.2685,0.2866,0.09173,0.2736,0.07320
213,881094802,0,17.42,25.56,114.50,948.0,0.10060,0.11460,0.16820,0.06597,...,18.07,28.07,120.40,1021.0,0.1243,0.1793,0.2803,0.10990,0.1603,0.06818
99,862548,0,14.42,19.77,94.48,642.5,0.09752,0.11410,0.09388,0.05839,...,16.33,30.86,109.50,826.4,0.1431,0.3026,0.3194,0.15650,0.2718,0.09353
401,904647,0,11.93,10.91,76.14,442.7,0.08872,0.05242,0.02606,0.01796,...,13.80,20.14,87.64,589.5,0.1374,0.1575,0.1514,0.06876,0.2460,0.07262
162,871201,0,19.59,18.15,130.70,1214.0,0.11200,0.16660,0.25080,0.12860,...,26.73,26.39,174.90,2232.0,0.1438,0.3846,0.6810,0.22470,0.3643,0.09223
57,857793,0,14.71,21.59,95.55,656.9,0.11370,0.13650,0.12930,0.08123,...,17.87,30.70,115.70,985.5,0.1368,0.4290,0.3587,0.18340,0.3698,0.10940
274,8911163,0,17.93,24.48,115.20,998.9,0.08855,0.07027,0.05699,0.04744,...,20.92,34.69,135.10,1320.0,0.1315,0.1806,0.2080,0.11360,0.2504,0.07948
324,89511501,0,12.20,15.21,78.01,457.9,0.08673,0.06545,0.01994,0.01692,...,13.75,21.38,91.11,583.1,0.1256,0.1928,0.1167,0.05556,0.2661,0.07961

Let's split the data as follows: 80% for training, 10% for validation and let's set 10% aside for our batch inference job. In addition, let's drop the 'id' field on the training set and validation set as 'id' is not a training feature. For our batch set however, we keep the 'id' feature. We'll want to filter it out prior to running our inferences so that the input data features match the ones of training set and then ultimately, we'll want to join it with inference result. We are however dropping the diagnosis attribute for the batch set since this is what we'll try to predict.

In [10]:
# data split in three sets, training, validation and batch inference
rand_split = np.random.rand(len(data))
train_list = rand_split < 0.8
val_list = (rand_split >= 0.8) & (rand_split < 0.9)
batch_list = rand_split >= 0.9

data_train = data[train_list].drop(["id"], axis=1)
data_val = data[val_list].drop(["id"], axis=1)
data_batch = data[batch_list].drop(["diagnosis"], axis=1)
data_batch_noID = data_batch.drop(["id"], axis=1)

Let's upload those data sets in S3

In [11]:
train_file = "train_data.csv"
data_train.to_csv(train_file, index=False, header=False)
sess.upload_data(train_file, key_prefix="{}/train".format(prefix))

validation_file = "validation_data.csv"
data_val.to_csv(validation_file, index=False, header=False)
sess.upload_data(validation_file, key_prefix="{}/validation".format(prefix))

batch_file = "batch_data.csv"
data_batch.to_csv(batch_file, index=False, header=False)
sess.upload_data(batch_file, key_prefix="{}/batch".format(prefix))

batch_file_noID = "batch_data_noID.csv"
data_batch_noID.to_csv(batch_file_noID, index=False, header=False)
sess.upload_data(batch_file_noID, key_prefix="{}/batch".format(prefix))

's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/batch/batch_data_noID.csv'

---

## Training job and model creation

The below cell uses the [SageMaker Python SDK](https://github.com/aws/sagemaker-python-sdk) to kick off the training job using both our training set and validation set. Not that the objective is set to 'binary:logistic' which trains a model to output a probability between 0 and 1 (here the probability of a tumor being malignant).

In [12]:
%%time
from time import gmtime, strftime

job_name = "xgb-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
output_location = "s3://{}/{}/output/{}".format(bucket, prefix, job_name)
image = sagemaker.image_uris.retrieve(
    framework="xgboost", region=boto3.Session().region_name, version="1.7-1"
)

sm_estimator = sagemaker.estimator.Estimator(
    image,
    role,
    instance_count=1,
    instance_type="ml.m5.xlarge",
    volume_size=50,
    input_mode="File",
    output_path=output_location,
    sagemaker_session=sess,
)

sm_estimator.set_hyperparameters(
    objective="binary:logistic",
    max_depth=5,
    eta=0.2,
    gamma=4,
    min_child_weight=6,
    subsample=0.8,
    verbosity=0,
    num_round=100,
)

train_data = sagemaker.inputs.TrainingInput(
    "s3://{}/{}/train".format(bucket, prefix),
    distribution="FullyReplicated",
    content_type="text/csv",
    s3_data_type="S3Prefix",
)
validation_data = sagemaker.inputs.TrainingInput(
    "s3://{}/{}/validation".format(bucket, prefix),
    distribution="FullyReplicated",
    content_type="text/csv",
    s3_data_type="S3Prefix",
)
data_channels = {"train": train_data, "validation": validation_data}

# Start training by calling the fit method in the estimator
sm_estimator.fit(inputs=data_channels, job_name=job_name, logs=True)

/opt/conda/lib/python3.12/site-packages/sagemaker/estimator.py:588: SageMakerV2DeprecationWarning: Estimator is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelTrainer` (`from sagemaker.train import ModelTrainer`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
Estimator is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelTrainer` (`from sagemaker.train import ModelTrainer`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
INFO:sagemaker:Creating training-job with name: xgb-2026-09-26-18-54-32

2026-09-26 18:54:33 Starting - Starting the training job...
2026-09-26 18:54:48 Starting - Preparing the instances for training...
2026-09-26 18:55:12 Downloading - Downloading input data...
2026-09-26 18:55:42 Downloading - Downloading the training image...
2026-09-26 18:56:23 Training - Training image download completed. Training in progress../miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26 18:56:35.273 ip-10-0-248-82.ec2.internal:7 INFO utils.py:28] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2026-09-26 18:56:35.345 ip-10-0-248-82.ec2.internal:7 INFO profiler_config_parser.py:111] User has disabled profiler.
[2026-09-26:18:56:35:INFO] Imported framework sagemaker_xgboost_container.training
[2026-09-26:18:56:35:INFO] Failed to parse hyperparameter objective value binary:logistic to Json.
Returning the value itself
[2026-09-26:18:56:35:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:18:56:35:INFO] Running XGBoost Sagemaker in algorithm mode
[2026-09-26:18:56:35:INFO] Determined 0 GPU(s) available on the instance.
[2026-09-26:18:56:35:INFO] Determined delimiter of CSV input is ','
[2026-09-26:18:56:35:INFO] Determined delimiter of CSV input is ','
[2026-09-26:18:56:35:INFO] File path /opt/ml/input/data/train of input files
[2026-09-26:18:56:35:INFO] Making smlinks from folder /opt/ml/input/data/train to folder /tmp/sagemaker_xgboost_input_data
[2026-09-26:18:56:35:INFO] creating symlink between Path /opt/ml/input/data/train/train_data.csv and destination /tmp/sagemaker_xgboost_input_data/train_data.csv-5391736931780393091
[2026-09-26:18:56:35:INFO] files path: /tmp/sagemaker_xgboost_input_data
[2026-09-26:18:56:35:INFO] Determined delimiter of CSV input is ','
[2026-09-26:18:56:35:INFO] File path /opt/ml/input/data/validation of input files
[2026-09-26:18:56:35:INFO] Making smlinks from folder /opt/ml/input/data/validation to folder /tmp/sagemaker_xgboost_input_data
[2026-09-26:18:56:35:INFO] creating symlink between Path /opt/ml/input/data/validation/validation_data.csv and destination /tmp/sagemaker_xgboost_input_data/validation_data.csv-8116650096494476147
[2026-09-26:18:56:35:INFO] files path: /tmp/sagemaker_xgboost_input_data
[2026-09-26:18:56:35:INFO] Determined delimiter of CSV input is ','
[2026-09-26:18:56:35:INFO] Single node training.
[2026-09-26:18:56:35:INFO] Train matrix has 456 rows and 30 columns
[2026-09-26:18:56:35:INFO] Validation matrix has 60 rows
[2026-09-26 18:56:35.717 ip-10-0-248-82.ec2.internal:7 INFO json_config.py:92] Creating hook from json_config at /opt/ml/input/config/debughookconfig.json.
[2026-09-26 18:56:35.718 ip-10-0-248-82.ec2.internal:7 INFO hook.py:206] tensorboard_dir has not been set for the hook. SMDebug will not be exporting tensorboard summaries.
[2026-09-26 18:56:35.719 ip-10-0-248-82.ec2.internal:7 INFO hook.py:259] Saving to /opt/ml/output/tensors
[2026-09-26 18:56:35.719 ip-10-0-248-82.ec2.internal:7 INFO state_store.py:77] The checkpoint config file /opt/ml/input/config/checkpointconfig.json does not exist.
[2026-09-26:18:56:35:INFO] Debug hook created from config
[2026-09-26 18:56:35.723 ip-10-0-248-82.ec2.internal:7 INFO hook.py:427] Monitoring the collections: metrics
[2026-09-26 18:56:35.725 ip-10-0-248-82.ec2.internal:7 INFO hook.py:491] Hook is writing from the hook with pid: 7
[0]#011train-logloss:0.51474#011validation-logloss:0.51474
[1]#011train-logloss:0.39443#011validation-logloss:0.39443
[2]#011train-logloss:0.30804#011validation-logloss:0.30804
[3]#011train-logloss:0.24360#011validation-logloss:0.24360
[4]#011train-logloss:0.19440#011validation-logloss:0.19440
[5]#011train-logloss:0.15621#011validation-logloss:0.15621
[6]#011train-logloss:0.12620#011validation-logloss:0.12620
[7]#011train-logloss:0.10241#011validation-logloss:0.10241
[8]#011train-logloss:0.08339#011validation-logloss:0.08339
[9]#011train-logloss:0.06815#011validation-logloss:0.06815
[10]#011train-logloss:0.05585#011validation-logloss:0.05585
[11]#011train-logloss:0.04596#011validation-logloss:0.04596
[12]#011train-logloss:0.03791#011validation-logloss:0.03791
[13]#011train-logloss:0.03136#011validation-logloss:0.03136
[14]#011train-logloss:0.02601#011validation-logloss:0.02601
[15]#011train-logloss:0.02166#011validation-logloss:0.02166
[16]#011train-logloss:0.01811#011validation-logloss:0.01811
[17]#011train-logloss:0.01521#011validation-logloss:0.01521
[18]#011train-logloss:0.01521#011validation-logloss:0.01521
[19]#011train-logloss:0.01521#011validation-logloss:0.01521
[20]#011train-logloss:0.01521#011validation-logloss:0.01521
[21]#011train-logloss:0.01521#011validation-logloss:0.01521
[22]#011train-logloss:0.01521#011validation-logloss:0.01521
[23]#011train-logloss:0.01521#011validation-logloss:0.01521
[24]#011train-logloss:0.01521#011validation-logloss:0.01521
[25]#011train-logloss:0.01521#011validation-logloss:0.01521
[26]#011train-logloss:0.01521#011validation-logloss:0.01521
[27]#011train-logloss:0.01521#011validation-logloss:0.01521
[28]#011train-logloss:0.01521#011validation-logloss:0.01521
[29]#011train-logloss:0.01521#011validation-logloss:0.01521
[30]#011train-logloss:0.01521#011validation-logloss:0.01521
[31]#011train-logloss:0.01521#011validation-logloss:0.01521
[32]#011train-logloss:0.01521#011validation-logloss:0.01521
[33]#011train-logloss:0.01521#011validation-logloss:0.01521
[34]#011train-logloss:0.01521#011validation-logloss:0.01521
[35]#011train-logloss:0.01521#011validation-logloss:0.01521
[36]#011train-logloss:0.01521#011validation-logloss:0.01521
[37]#011train-logloss:0.01521#011validation-logloss:0.01521
[38]#011train-logloss:0.01521#011validation-logloss:0.01521
[39]#011train-logloss:0.01521#011validation-logloss:0.01521
[40]#011train-logloss:0.01521#011validation-logloss:0.01521
[41]#011train-logloss:0.01521#011validation-logloss:0.01521
[42]#011train-logloss:0.01521#011validation-logloss:0.01521
[43]#011train-logloss:0.01521#011validation-logloss:0.01521
[44]#011train-logloss:0.01521#011validation-logloss:0.01521
[45]#011train-logloss:0.01521#011validation-logloss:0.01521
[46]#011train-logloss:0.01521#011validation-logloss:0.01521
[47]#011train-logloss:0.01521#011validation-logloss:0.01521
[48]#011train-logloss:0.01521#011validation-logloss:0.01521
[49]#011train-logloss:0.01521#011validation-logloss:0.01521
[50]#011train-logloss:0.01521#011validation-logloss:0.01521
[51]#011train-logloss:0.01521#011validation-logloss:0.01521
[52]#011train-logloss:0.01521#011validation-logloss:0.01521
[53]#011train-logloss:0.01521#011validation-logloss:0.01521
[54]#011train-logloss:0.01521#011validation-logloss:0.01521
[55]#011train-logloss:0.01521#011validation-logloss:0.01521
[56]#011train-logloss:0.01521#011validation-logloss:0.01521
[57]#011train-logloss:0.01521#011validation-logloss:0.01521
[58]#011train-logloss:0.01521#011validation-logloss:0.01521
[59]#011train-logloss:0.01521#011validation-logloss:0.01521
[60]#011train-logloss:0.01521#011validation-logloss:0.01521
[61]#011train-logloss:0.01521#011validation-logloss:0.01521
[62]#011train-logloss:0.01521#011validation-logloss:0.01521
[63]#011train-logloss:0.01521#011validation-logloss:0.01521
[64]#011train-logloss:0.01521#011validation-logloss:0.01521
[65]#011train-logloss:0.01521#011validation-logloss:0.01521
[66]#011train-logloss:0.01521#011validation-logloss:0.01521
[67]#011train-logloss:0.01521#011validation-logloss:0.01521
[68]#011train-logloss:0.01521#011validation-logloss:0.01521
[69]#011train-logloss:0.01521#011validation-logloss:0.01521
[70]#011train-logloss:0.01521#011validation-logloss:0.01521
[71]#011train-logloss:0.01521#011validation-logloss:0.01521
[72]#011train-logloss:0.01521#011validation-logloss:0.01521
[73]#011train-logloss:0.01521#011validation-logloss:0.01521
[74]#011train-logloss:0.01521#011validation-logloss:0.01521
[75]#011train-logloss:0.01521#011validation-logloss:0.01521
[76]#011train-logloss:0.01521#011validation-logloss:0.01521
[77]#011train-logloss:0.01521#011validation-logloss:0.01521
[78]#011train-logloss:0.01521#011validation-logloss:0.01521
[79]#011train-logloss:0.01521#011validation-logloss:0.01521
[80]#011train-logloss:0.01521#011validation-logloss:0.01521
[81]#011train-logloss:0.01521#011validation-logloss:0.01521
[82]#011train-logloss:0.01521#011validation-logloss:0.01521
[83]#011train-logloss:0.01521#011validation-logloss:0.01521
[84]#011train-logloss:0.01521#011validation-logloss:0.01521
[85]#011train-logloss:0.01521#011validation-logloss:0.01521
[86]#011train-logloss:0.01521#011validation-logloss:0.01521
[87]#011train-logloss:0.01521#011validation-logloss:0.01521
[88]#011train-logloss:0.01521#011validation-logloss:0.01521
[89]#011train-logloss:0.01521#011validation-logloss:0.01521
[90]#011train-logloss:0.01521#011validation-logloss:0.01521
[91]#011train-logloss:0.01521#011validation-logloss:0.01521
[92]#011train-logloss:0.01521#011validation-logloss:0.01521
[93]#011train-logloss:0.01521#011validation-logloss:0.01521
[94]#011train-logloss:0.01521#011validation-logloss:0.01521
[95]#011train-logloss:0.01521#011validation-logloss:0.01521
[96]#011train-logloss:0.01521#011validation-logloss:0.01521
[97]#011train-logloss:0.01521#011validation-logloss:0.01521
[98]#011train-logloss:0.01521#011validation-logloss:0.01521
[99]#011train-logloss:0.01521#011validation-logloss:0.01521

2026-09-26 18:56:56 Uploading - Uploading generated training model
2026-09-26 18:56:56 Completed - Training job completed
Training seconds: 104
Billable seconds: 104
CPU times: user 382 ms, sys: 17.8 ms, total: 400 ms
Wall time: 2min 47s

---

## Batch Transform

In SageMaker Batch Transform, we introduced 3 new attributes - __input_filter__, __join_source__ and __output_filter__. In the below cell, we use the [SageMaker Python SDK](https://github.com/aws/sagemaker-python-sdk) to kick-off several Batch Transform jobs using different configurations of these 3 new attributes. Please refer to [this page](https://docs.aws.amazon.com/sagemaker/latest/dg/batch-transform-data-processing.html) to learn more about how to use them.

#### 1. Create a transform job with the default configurations
Let's first skip these 3 new attributes and inspect the inference results. We'll use it as a baseline to compare to the results with data processing.

In [13]:
%%time

sm_transformer = sm_estimator.transformer(1, "ml.m5.xlarge")

# start a transform job
input_location = "s3://{}/{}/batch/{}".format(
    bucket, prefix, batch_file_noID
)  # use input data without ID column
sm_transformer.transform(input_location, content_type="text/csv", split_type="Line")
sm_transformer.wait()

/opt/conda/lib/python3.12/site-packages/sagemaker/model.py:347: SageMakerV2DeprecationWarning: Model is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelBuilder` (`from sagemaker.serve import ModelBuilder`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
WARNING:sagemaker.deprecations:Model is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelBuilder` (`from sagemaker.serve import ModelBuilder`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
INFO:sagemaker:Creating model with name: sagemaker-xgboost-2026-09-26-19-05-54-808
/opt/conda/lib/python3.12/site-packages/sagemaker/transformer.py:115: SageMakerV2DeprecationWarning: Transformer is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `sagemaker.core.shapes.TransformJob`.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
WARNING:sagemaker.deprecations:Transformer is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `sagemaker.core.shapes.TransformJob`.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
INFO:sagemaker:Creating transform job with name: sagemaker-xgboost-2026-09-26-19-05-55-364

........................
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:09:56:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:56:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:56:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-09-26 19:09:56 +0000] [17] [INFO] Starting gunicorn 23.0.0
[2026-09-26 19:09:56 +0000] [17] [INFO] Listening at: unix:/tmp/gunicorn.sock (17)
[2026-09-26 19:09:56 +0000] [17] [INFO] Using worker: gevent
[2026-09-26 19:09:56 +0000] [22] [INFO] Booting worker with pid: 22
[2026-09-26 19:09:56 +0000] [23] [INFO] Booting worker with pid: 23
[2026-09-26 19:09:56 +0000] [24] [INFO] Booting worker with pid: 24
[2026-09-26 19:09:56 +0000] [25] [INFO] Booting worker with pid: 25
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:59:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:59:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:59:INFO] Model objective : binary:logistic
[2026-09-26:19:10:01:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:10:01 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:10:02:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:10:02 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:10:02:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:10:02:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [26/Sep/2026:19:10:02 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
2026-09-26T19:10:02.021:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:09:56:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:56:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:56:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:09:56:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:56:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:56:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
}
[2026-09-26 19:09:56 +0000] [17] [INFO] Starting gunicorn 23.0.0
[2026-09-26 19:09:56 +0000] [17] [INFO] Listening at: unix:/tmp/gunicorn.sock (17)
[2026-09-26 19:09:56 +0000] [17] [INFO] Using worker: gevent
[2026-09-26 19:09:56 +0000] [22] [INFO] Booting worker with pid: 22
[2026-09-26 19:09:56 +0000] [17] [INFO] Starting gunicorn 23.0.0
[2026-09-26 19:09:56 +0000] [17] [INFO] Listening at: unix:/tmp/gunicorn.sock (17)
[2026-09-26 19:09:56 +0000] [17] [INFO] Using worker: gevent
[2026-09-26 19:09:56 +0000] [22] [INFO] Booting worker with pid: 22
[2026-09-26 19:09:56 +0000] [23] [INFO] Booting worker with pid: 23
[2026-09-26 19:09:56 +0000] [24] [INFO] Booting worker with pid: 24
[2026-09-26 19:09:56 +0000] [25] [INFO] Booting worker with pid: 25
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26 19:09:56 +0000] [23] [INFO] Booting worker with pid: 23
[2026-09-26 19:09:56 +0000] [24] [INFO] Booting worker with pid: 24
[2026-09-26 19:09:56 +0000] [25] [INFO] Booting worker with pid: 25
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:59:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:59:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:59:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:58:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:58:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:58:INFO] Model objective : binary:logistic
[2026-09-26:19:09:59:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:09:59:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:09:59:INFO] Model objective : binary:logistic
[2026-09-26:19:10:01:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:10:01 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:10:02:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:10:02 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:10:02:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:10:02:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [26/Sep/2026:19:10:02 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
[2026-09-26:19:10:01:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:10:01 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:10:02:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:10:02 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:10:02:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:10:02:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [26/Sep/2026:19:10:02 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
2026-09-26T19:10:02.021:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD
CPU times: user 433 ms, sys: 17.3 ms, total: 450 ms
Wall time: 4min 34s

Let's inspect the output of the Batch Transform job in S3. It should show the list probabilities of tumors being malignant.

In [16]:
import re


def get_csv_output_from_s3(s3uri, batch_file):
    file_name = "{}.out".format(batch_file)
    match = re.match("s3://([^/]+)/(.*)", "{}/{}".format(s3uri, file_name))
    output_bucket, output_prefix = match.group(1), match.group(2)
    s3.download_file(output_bucket, output_prefix, file_name)
    return pd.read_csv(file_name, sep=",", header=None)

In [17]:
output_df = get_csv_output_from_s3(sm_transformer.output_path, batch_file_noID)
output_df.head(8)

          0
0  0.015096
1  0.015096
2  0.015096
3  0.015096
4  0.015096
5  0.015096
6  0.015096
7  0.015096

#### 2. Join the input and the prediction results 
Now, let's associate the prediction results with their corresponding input records. We can also use the __input_filter__ to exclude the ID column easily and there's no need to have a separate file in S3.

* Set __input_filter__ to "$[1:]": indicates that we are excluding column 0 (the 'ID') before processing the inferences and keeping everything from column 1 to the last column (all the features or predictors)  
  
  
* Set __join_source__ to "Input": indicates our desire to join the input data with the inference results  

* Leave __output_filter__ to default ('$'), indicating that the joined input and inference results be will saved as output.

In [18]:
# content_type / accept and split_type / assemble_with are required to use IO joining feature
sm_transformer.assemble_with = "Line"
sm_transformer.accept = "text/csv"

# start a transform job
input_location = "s3://{}/{}/batch/{}".format(
    bucket, prefix, batch_file
)  # use input data with ID column cause InputFilter will filter it out
sm_transformer.transform(
    input_location,
    split_type="Line",
    content_type="text/csv",
    input_filter="$[1:]",
    join_source="Input",
)
sm_transformer.wait()

INFO:sagemaker:Creating transform job with name: sagemaker-xgboost-2026-09-26-19-16-03-984

....................../miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:19:48:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:48:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:48:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-09-26 19:19:48 +0000] [18] [INFO] Starting gunicorn 23.0.0
[2026-09-26 19:19:48 +0000] [18] [INFO] Listening at: unix:/tmp/gunicorn.sock (18)
[2026-09-26 19:19:48 +0000] [18] [INFO] Using worker: gevent
[2026-09-26 19:19:48 +0000] [23] [INFO] Booting worker with pid: 23
[2026-09-26 19:19:48 +0000] [24] [INFO] Booting worker with pid: 24
[2026-09-26 19:19:48 +0000] [25] [INFO] Booting worker with pid: 25
[2026-09-26 19:19:48 +0000] [26] [INFO] Booting worker with pid: 26
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:51:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:51:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:51:INFO] Model objective : binary:logistic
[2026-09-26:19:19:53:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:53 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:19:53:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:53 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:54:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:54:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
2026-09-26T19:19:54.033:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD

/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:19:48:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:48:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:48:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:48:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:48:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-09-26 19:19:48 +0000] [18] [INFO] Starting gunicorn 23.0.0
[2026-09-26 19:19:48 +0000] [18] [INFO] Listening at: unix:/tmp/gunicorn.sock (18)
[2026-09-26 19:19:48 +0000] [18] [INFO] Using worker: gevent
[2026-09-26 19:19:48 +0000] [23] [INFO] Booting worker with pid: 23
[2026-09-26:19:19:48:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-09-26 19:19:48 +0000] [18] [INFO] Starting gunicorn 23.0.0
[2026-09-26 19:19:48 +0000] [18] [INFO] Listening at: unix:/tmp/gunicorn.sock (18)
[2026-09-26 19:19:48 +0000] [18] [INFO] Using worker: gevent
[2026-09-26 19:19:48 +0000] [23] [INFO] Booting worker with pid: 23
[2026-09-26 19:19:48 +0000] [24] [INFO] Booting worker with pid: 24
[2026-09-26 19:19:48 +0000] [25] [INFO] Booting worker with pid: 25
[2026-09-26 19:19:48 +0000] [26] [INFO] Booting worker with pid: 26
[2026-09-26 19:19:48 +0000] [24] [INFO] Booting worker with pid: 24
[2026-09-26 19:19:48 +0000] [25] [INFO] Booting worker with pid: 25
[2026-09-26 19:19:48 +0000] [26] [INFO] Booting worker with pid: 26
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
/miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:50:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:50:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:50:INFO] Model objective : binary:logistic
[2026-09-26:19:19:51:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:51:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:51:INFO] Model objective : binary:logistic
[2026-09-26:19:19:51:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:51:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-09-26:19:19:51:INFO] Model objective : binary:logistic
[2026-09-26:19:19:53:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:53 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:19:53:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:53 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:54:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
[2026-09-26:19:19:54:INFO] No GPUs detected (normal if no gpus installed)
[2026-09-26:19:19:54:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.9/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
169.254.255.130 - - [26/Sep/2026:19:19:54 +0000] "POST /invocations HTTP/1.1" 200 1113 "-" "Go-http-client/1.1"
2026-09-26T19:19:54.033:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD

Let's inspect the output of the Batch Transform job in S3. It should show the list of tumors identified by their original feature columns and their corresponding probabilities of being malignant.

In [14]:
output_df = get_csv_output_from_s3(sm_transformer.output_path, batch_file)
output_df.head(8)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,84610002,15.780,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.06606,0.1842,...,27.28,136.50,1299.0,0.1396,0.56090,0.39650,0.18100,0.3792,0.10480,0.978181
1,849014,19.810,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.09498,0.1582,...,30.88,186.80,2398.0,0.1512,0.31500,0.53720,0.23880,0.2768,0.07615,0.994243
2,857343,11.760,21.60,74.72,427.9,0.08637,0.04966,0.01657,0.01115,0.1495,...,25.72,82.98,516.5,0.1085,0.08615,0.05523,0.03715,0.2433,0.06563,0.018018
3,85759902,11.520,18.75,73.34,409.0,0.09524,0.05473,0.03036,0.02278,0.1920,...,22.47,81.81,506.2,0.1249,0.08720,0.09076,0.06316,0.3306,0.07036,0.006963
4,857637,19.210,18.57,125.50,1152.0,0.10530,0.12670,0.13230,0.08994,0.1917,...,28.14,170.10,2145.0,0.1624,0.35110,0.38790,0.20910,0.3537,0.08294,0.982709
5,859283,14.780,23.94,97.40,668.3,0.11720,0.14790,0.12670,0.09029,0.1953,...,33.39,114.60,925.1,0.1648,0.34160,0.30240,0.16140,0.3321,0.08911,0.990804
6,859464,9.465,21.01,60.11,269.4,0.10440,0.07773,0.02172,0.01504,0.1717,...,31.56,67.03,330.7,0.1548,0.16640,0.09412,0.06517,0.2878,0.09211,0.047220
7,8610862,20.180,23.97,143.70,1245.0,0.12860,0.34540,0.37540,0.16040,0.2906,...,31.72,170.30,1623.0,0.1639,0.61640,0.76810,0.25080,0.5440,0.09964,0.994243

#### 3. Update the output filter to keep only ID and prediction results
Let's change __output_filter__ to "$[0,-1]", indicating that when presenting the output, we only want to keep column 0 (the 'ID') and the last column (the inference result i.e. the probability of a given tumor to be malignant)

In [15]:
# start another transform job
sm_transformer.transform(
    input_location,
    split_type="Line",
    content_type="text/csv",
    input_filter="$[1:]",
    join_source="Input",
    output_filter="$[0,-1]",
)
sm_transformer.wait()

INFO:sagemaker:Creating transform job with name: sagemaker-xgboost-2023-08-22-06-08-34-077

......................................[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2023-08-22 06:14:52 +0000] [19] [INFO] Starting gunicorn 19.10.0
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2023-08-22 06:14:52 +0000] [19] [INFO] Starting gunicorn 19.10.0
[2023-08-22 06:14:52 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2023-08-22 06:14:52 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2023-08-22 06:14:52 +0000] [25] [INFO] Booting worker with pid: 25
[2023-08-22 06:14:52 +0000] [26] [INFO] Booting worker with pid: 26
[2023-08-22 06:14:52 +0000] [27] [INFO] Booting worker with pid: 27
[2023-08-22 06:14:52 +0000] [28] [INFO] Booting worker with pid: 28
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:54:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22 06:14:52 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2023-08-22 06:14:52 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2023-08-22 06:14:52 +0000] [25] [INFO] Booting worker with pid: 25
[2023-08-22 06:14:52 +0000] [26] [INFO] Booting worker with pid: 26
[2023-08-22 06:14:52 +0000] [27] [INFO] Booting worker with pid: 27
[2023-08-22 06:14:52 +0000] [28] [INFO] Booting worker with pid: 28
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:54:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:54:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:54:INFO] Model objective : binary:logistic
[2023-08-22:06:14:54:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:54:INFO] Model objective : binary:logistic
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "POST /invocations HTTP/1.1" 200 1343 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "POST /invocations HTTP/1.1" 200 1343 "-" "Go-http-client/1.1"
2023-08-22T06:14:58.210:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD

[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:51:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2023-08-22 06:14:52 +0000] [19] [INFO] Starting gunicorn 19.10.0
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2023-08-22 06:14:52 +0000] [19] [INFO] Starting gunicorn 19.10.0
[2023-08-22 06:14:52 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2023-08-22 06:14:52 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2023-08-22 06:14:52 +0000] [25] [INFO] Booting worker with pid: 25
[2023-08-22 06:14:52 +0000] [26] [INFO] Booting worker with pid: 26
[2023-08-22 06:14:52 +0000] [27] [INFO] Booting worker with pid: 27
[2023-08-22 06:14:52 +0000] [28] [INFO] Booting worker with pid: 28
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:54:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22 06:14:52 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2023-08-22 06:14:52 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2023-08-22 06:14:52 +0000] [25] [INFO] Booting worker with pid: 25
[2023-08-22 06:14:52 +0000] [26] [INFO] Booting worker with pid: 26
[2023-08-22 06:14:52 +0000] [27] [INFO] Booting worker with pid: 27
[2023-08-22 06:14:52 +0000] [28] [INFO] Booting worker with pid: 28
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:53:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:53:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:53:INFO] Model objective : binary:logistic
[2023-08-22:06:14:54:INFO] No GPUs detected (normal if no gpus installed)
[2023-08-22:06:14:54:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:54:INFO] Model objective : binary:logistic
[2023-08-22:06:14:54:INFO] Loading the model from /opt/ml/model/xgboost-model
[2023-08-22:06:14:54:INFO] Model objective : binary:logistic
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "POST /invocations HTTP/1.1" 200 1343 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2023-08-22:06:14:58:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:122: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [22/Aug/2023:06:14:58 +0000] "POST /invocations HTTP/1.1" 200 1343 "-" "Go-http-client/1.1"
2023-08-22T06:14:58.210:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD

Now, let's inspect the output of the Batch Transform job in S3 again. It should show 2 columns: the ID and their corresponding probabilities of being malignant.

In [20]:
output_df = get_csv_output_from_s3(sm_transformer.output_path, batch_file)
output_df.head(8)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,844981,13.00,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.093530,0.2350,...,30.73,106.20,739.3,0.17030,0.54010,0.539000,0.20600,0.4378,0.10720,0.015096
1,849014,19.81,22.15,130.00,1260.0,0.09831,0.10270,0.147900,0.094980,0.1582,...,30.88,186.80,2398.0,0.15120,0.31500,0.537200,0.23880,0.2768,0.07615,0.015096
2,855133,14.99,25.20,95.54,698.8,0.09387,0.05131,0.023980,0.028990,0.1565,...,25.20,95.54,698.8,0.09387,0.05131,0.023980,0.02899,0.1565,0.05504,0.015096
3,855138,13.48,20.82,88.40,559.2,0.10160,0.12550,0.106300,0.054390,0.1720,...,26.02,107.30,740.4,0.16100,0.42250,0.503000,0.22580,0.2807,0.10710,0.015096
4,857155,12.05,14.63,78.04,449.3,0.10310,0.09092,0.065920,0.027490,0.1675,...,20.70,89.88,582.6,0.14940,0.21560,0.305000,0.06548,0.2747,0.08301,0.015096
5,857810,13.05,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,0.1819,...,22.25,90.24,624.1,0.10210,0.06191,0.001845,0.01111,0.2439,0.06289,0.015096
6,858970,10.17,14.88,64.55,311.9,0.11340,0.08061,0.010840,0.012900,0.2743,...,17.45,69.86,368.6,0.12750,0.09866,0.021680,0.02579,0.3557,0.08020,0.015096
7,85922302,12.68,23.84,82.69,499.0,0.11220,0.12620,0.112800,0.068730,0.1905,...,33.47,111.80,888.3,0.18510,0.40610,0.402400,0.17160,0.3383,0.10310,0.015096

create_model(role=role, image_uri=XGBOOST_IMAGE)In summary, we can use newly introduced 3 attributes - __input_filter__, __join_source__, __output_filter__ to 
1. Filter / select useful features from the input dataset. e.g. exclude ID columns.
2. Associate the prediction results with their corresponding input records.
3. Filter the original or joined results before saving to S3. e.g. keep ID and probability columns only.

## Upload the Sagemaker Model created during our training job to the Sagemaker Model Registry

In [21]:
sagemaker = boto3.client("sagemaker")

model_name = job_name
print(model_name)


info = sagemaker.describe_training_job(TrainingJobName=model_name)
model_data = info["ModelArtifacts"]["S3ModelArtifacts"]

primary_container = {"Image": image, "ModelDataUrl": model_data}

# Save our model to the Sagemaker Model Registry
create_model_response = sagemaker.create_model(
    ModelName=model_name, ExecutionRoleArn=role, PrimaryContainer=primary_container
)

print(create_model_response["ModelArn"])

xgb-2026-09-26-18-54-32
arn:aws:sagemaker:us-east-1:682123396235:model/xgb-2026-09-26-18-54-32

In [22]:
# Inspect Training Job Details
info

{'TrainingJobName': 'xgb-2026-09-26-18-54-32',
 'TrainingJobArn': 'arn:aws:sagemaker:us-east-1:682123396235:training-job/xgb-2026-09-26-18-54-32',
 'ModelArtifacts': {'S3ModelArtifacts': 's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/output/xgb-2026-09-26-18-54-32/xgb-2026-09-26-18-54-32/output/model.tar.gz'},
 'TrainingJobStatus': 'Completed',
 'SecondaryStatus': 'Completed',
 'HyperParameters': {'eta': '0.2',
  'gamma': '4',
  'max_depth': '5',
  'min_child_weight': '6',
  'num_round': '100',
  'objective': 'binary:logistic',
  'subsample': '0.8',
  'verbosity': '0'},
 'AlgorithmSpecification': {'TrainingImage': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.7-1',
  'TrainingInputMode': 'File',
  'MetricDefinitions': [{'Name': 'train:mae',
    'Regex': '.*\\[[0-9]+\\].*#011train-mae:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:aucpr',
    'Regex': '.*\\[[0-9]+\\].*#011validation-aucpr:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:f1_binary',
    'Regex': '.*\\[[0-9]+\\].*#011validation-f1_binary:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:mae',
    'Regex': '.*\\[[0-9]+\\].*#011validation-mae:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:logloss',
    'Regex': '.*\\[[0-9]+\\].*#011validation-logloss:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:f1',
    'Regex': '.*\\[[0-9]+\\].*#011validation-f1:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:accuracy',
    'Regex': '.*\\[[0-9]+\\].*#011train-accuracy:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:mse',
    'Regex': '.*\\[[0-9]+\\].*#011train-mse:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:recall',
    'Regex': '.*\\[[0-9]+\\].*#011validation-recall:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:poisson-nloglik',
    'Regex': '.*\\[[0-9]+\\].*#011validation-poisson-nloglik:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:precision',
    'Regex': '.*\\[[0-9]+\\].*#011validation-precision:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:error',
    'Regex': '.*\\[[0-9]+\\].*#011train-error:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:ndcg',
    'Regex': '.*\\[[0-9]+\\].*#011train-ndcg:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:map',
    'Regex': '.*\\[[0-9]+\\].*#011validation-map:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:f1_binary',
    'Regex': '.*\\[[0-9]+\\].*#011train-f1_binary:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:auc',
    'Regex': '.*\\[[0-9]+\\].*#011validation-auc:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:auc',
    'Regex': '.*\\[[0-9]+\\].*#011train-auc:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:error',
    'Regex': '.*\\[[0-9]+\\].*#011validation-error:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:poisson-nloglik',
    'Regex': '.*\\[[0-9]+\\].*#011train-poisson-nloglik:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:rmse',
    'Regex': '.*\\[[0-9]+\\].*#011train-rmse:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:logloss',
    'Regex': '.*\\[[0-9]+\\].*#011train-logloss:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:accuracy',
    'Regex': '.*\\[[0-9]+\\].*#011validation-accuracy:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:aucpr',
    'Regex': '.*\\[[0-9]+\\].*#011train-aucpr:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:balanced_accuracy',
    'Regex': '.*\\[[0-9]+\\].*#011validation-balanced_accuracy:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:rmse',
    'Regex': '.*\\[[0-9]+\\].*#011validation-rmse:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:mse',
    'Regex': '.*\\[[0-9]+\\].*#011validation-mse:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'validation:ndcg',
    'Regex': '.*\\[[0-9]+\\].*#011validation-ndcg:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:f1',
    'Regex': '.*\\[[0-9]+\\].*#011train-f1:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'},
   {'Name': 'train:map',
    'Regex': '.*\\[[0-9]+\\].*#011train-map:([-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?).*'}],
  'EnableSageMakerMetricsTimeSeries': False},
 'RoleArn': 'arn:aws:iam::682123396235:role/LabRole',
 'InputDataConfig': [{'ChannelName': 'train',
   'DataSource': {'S3DataSource': {'S3DataType': 'S3Prefix',
     'S3Uri': 's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/train',
     'S3DataDistributionType': 'FullyReplicated'}},
   'ContentType': 'text/csv',
   'CompressionType': 'None',
   'RecordWrapperType': 'None'},
  {'ChannelName': 'validation',
   'DataSource': {'S3DataSource': {'S3DataType': 'S3Prefix',
     'S3Uri': 's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/validation',
     'S3DataDistributionType': 'FullyReplicated'}},
   'ContentType': 'text/csv',
   'CompressionType': 'None',
   'RecordWrapperType': 'None'}],
 'OutputDataConfig': {'KmsKeyId': '',
  'S3OutputPath': 's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/output/xgb-2026-09-26-18-54-32',
  'CompressionType': 'GZIP'},
 'ResourceConfig': {'InstanceType': 'ml.m5.xlarge',
  'InstanceCount': 1,
  'VolumeSizeInGB': 50},
 'StoppingCondition': {'MaxRuntimeInSeconds': 86400},
 'CreationTime': datetime.datetime(2026, 9, 26, 18, 54, 32, 725000, tzinfo=tzlocal()),
 'TrainingStartTime': datetime.datetime(2026, 9, 26, 18, 55, 12, 105000, tzinfo=tzlocal()),
 'TrainingEndTime': datetime.datetime(2026, 9, 26, 18, 56, 56, 384000, tzinfo=tzlocal()),
 'LastModifiedTime': datetime.datetime(2026, 9, 26, 18, 56, 56, 827000, tzinfo=tzlocal()),
 'SecondaryStatusTransitions': [{'Status': 'Starting',
   'StartTime': datetime.datetime(2026, 9, 26, 18, 54, 32, 725000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 9, 26, 18, 55, 12, 105000, tzinfo=tzlocal()),
   'StatusMessage': 'Preparing the instances for training'},
  {'Status': 'Downloading',
   'StartTime': datetime.datetime(2026, 9, 26, 18, 55, 12, 105000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 9, 26, 18, 56, 23, 266000, tzinfo=tzlocal()),
   'StatusMessage': 'Downloading the training image'},
  {'Status': 'Training',
   'StartTime': datetime.datetime(2026, 9, 26, 18, 56, 23, 266000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 9, 26, 18, 56, 43, 726000, tzinfo=tzlocal()),
   'StatusMessage': 'Training image download completed. Training in progress.'},
  {'Status': 'Uploading',
   'StartTime': datetime.datetime(2026, 9, 26, 18, 56, 43, 726000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 9, 26, 18, 56, 56, 384000, tzinfo=tzlocal()),
   'StatusMessage': 'Uploading generated training model'},
  {'Status': 'Completed',
   'StartTime': datetime.datetime(2026, 9, 26, 18, 56, 56, 384000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 9, 26, 18, 56, 56, 384000, tzinfo=tzlocal()),
   'StatusMessage': 'Training job completed'}],
 'FinalMetricDataList': [{'MetricName': 'validation:logloss',
   'Value': 0.015209999866783619,
   'Timestamp': datetime.datetime(2026, 9, 26, 18, 56, 36, tzinfo=tzlocal())},
  {'MetricName': 'train:logloss',
   'Value': 0.015209999866783619,
   'Timestamp': datetime.datetime(2026, 9, 26, 18, 56, 36, tzinfo=tzlocal())}],
 'EnableNetworkIsolation': False,
 'EnableInterContainerTrafficEncryption': False,
 'EnableManagedSpotTraining': False,
 'TrainingTimeInSeconds': 104,
 'BillableTimeInSeconds': 104,
 'DebugHookConfig': {'S3OutputPath': 's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/output/xgb-2026-09-26-18-54-32',
  'CollectionConfigurations': []},
 'ProfilerConfig': {'S3OutputPath': 's3://sagemaker-us-east-1-682123396235/DEMO-breast-cancer-prediction-xgboost-highlevel/output/xgb-2026-09-26-18-54-32',
  'ProfilingIntervalInMilliseconds': 500,
  'DisableProfiler': False},
 'ProfilingStatus': 'Enabled',
 'ResponseMetadata': {'RequestId': '672b16fb-af13-4428-9c26-d03b374aa52b',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '672b16fb-af13-4428-9c26-d03b374aa52b',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '7455',
   'date': 'Sat, 26 Sep 2026 19:23:06 GMT'},
  'RetryAttempts': 0}}

In [23]:
# Create Endpoint Configuration


# Create an endpoint config name. Here we create one based on the date  
# so it we can search endpoints based on creation time.
endpoint_config_name = 'lab4-1-endpoint-config' + strftime("%Y-%m-%d-%H-%M-%S", gmtime())                            
                            
instance_type = 'ml.m5.xlarge'

endpoint_config_response = sagemaker.create_endpoint_config(
    EndpointConfigName=endpoint_config_name, # You will specify this name in a CreateEndpoint request.
    # List of ProductionVariant objects, one for each model that you want to host at this endpoint.
    ProductionVariants=[
        {
            "VariantName": "variant1", # The name of the production variant.
            "ModelName": model_name, 
            "InstanceType": instance_type, # Specify the compute instance type.
            "InitialInstanceCount": 1 # Number of instances to launch initially.
        }
    ]
)

print(f"Created EndpointConfig: {endpoint_config_response['EndpointConfigArn']}")

Created EndpointConfig: arn:aws:sagemaker:us-east-1:682123396235:endpoint-config/lab4-1-endpoint-config2026-09-26-19-27-27

In [24]:
# Deploy our model to real-time endpoint

endpoint_name = 'lab4-1-endpoint' + strftime("%Y-%m-%d-%H-%M-%S", gmtime())                            


create_endpoint_response = sagemaker.create_endpoint(
                                            EndpointName=endpoint_name, 
                                            EndpointConfigName=endpoint_config_name)

In [25]:
# Wait for endpoint to spin up

sagemaker.describe_endpoint(EndpointName=endpoint_name)

while True:
    print("Getting Job Status")
    res = sagemaker.describe_endpoint(EndpointName=endpoint_name)
    state = res["EndpointStatus"]
    
    if state == "InService":
        print("Endpoint in Service")
        break
    elif state == "Creating":
        print("Endpoint still creating...")
        sleep(60)
    else:
        print("Endpoint Creation Error - Check Sagemaker Console")
        break

Getting Job Status
Endpoint in Service

In [26]:
# Invoke Endpoint

sagemaker_runtime = boto3.client("sagemaker-runtime", region_name=region)

response = sagemaker_runtime.invoke_endpoint(
                            EndpointName=endpoint_name,
                            ContentType='text/csv',
                            Body=data_batch_noID.to_csv(header=None, index=False).strip('\n').split('\n')[0]
                            )
print(response['Body'].read().decode('utf-8'))

0.015096119605004787

In [27]:
# Examine Response Body

response

{'ResponseMetadata': {'RequestId': '77917c29-5d29-4db1-9d60-9f7850f327ac',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '77917c29-5d29-4db1-9d60-9f7850f327ac',
   'x-amzn-invoked-production-variant': 'variant1',
   'date': 'Sat, 26 Sep 2026 19:32:06 GMT',
   'content-type': 'text/csv; charset=utf-8',
   'content-length': '21',
   'connection': 'keep-alive'},
  'RetryAttempts': 0},
 'ContentType': 'text/csv; charset=utf-8',
 'InvokedProductionVariant': 'variant1',
 'Body': <botocore.response.StreamingBody at 0x7f665c7e7730>}

In [45]:
# Delete Endpoint

sagemaker.delete_endpoint(EndpointName=endpoint_name)

{'ResponseMetadata': {'RequestId': 'c2b381e2-33a0-4b70-8732-fbaa44fab5a0',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'c2b381e2-33a0-4b70-8732-fbaa44fab5a0',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '0',
   'date': 'Tue, 22 Aug 2023 07:10:18 GMT'},
  'RetryAttempts': 0}}

## Notebook CI Test Results

This notebook was tested in multiple regions. The test results are as follows, except for us-west-2 which is shown at the top of the notebook.

![This us-east-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/us-east-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This us-east-2 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/us-east-2/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This us-west-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/us-west-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This ca-central-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/ca-central-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This sa-east-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/sa-east-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This eu-west-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/eu-west-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This eu-west-2 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/eu-west-2/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This eu-west-3 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/eu-west-3/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This eu-central-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/eu-central-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This eu-north-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/eu-north-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This ap-southeast-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/ap-southeast-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This ap-southeast-2 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/ap-southeast-2/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This ap-northeast-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/ap-northeast-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This ap-northeast-2 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/ap-northeast-2/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)

![This ap-south-1 badge failed to load. Check your device's internet connectivity, otherwise the service is currently unavailable](https://h75twx4l60.execute-api.us-west-2.amazonaws.com/sagemaker-nb/ap-south-1/sagemaker_batch_transform|batch_transform_associate_predictions_with_input|Batch Transform - breast cancer prediction with high level SDK.ipynb)